cursor            #c4c6cb
cursor_text_color #2d3134

foreground            #e5e2e1
background            #0e0e0e
selection_foreground  #e5e2e1
selection_background  #626569
url_color             #c4c6cb

#: black
color0  #0a0a17
color8  #59596d
#: red
color1  #7F7E80
color9  #7F7E80
#: green — neutral surface variant
color2  #909092
color10  #909092
#: yellow — mild accent
color3  #A79F9D
color11  #A79F9D
#: blue — primary accent
color4  #B2B1B2
color12  #B2B1B2
#: magenta — secondary accent
color5  #C0BEC0
color13  #C0BEC0
#: cyan — tertiary
color6  #CCCBCC
color14  #CCCBCC
#: white
color7  #c1c1c5
color15  #c1c1c5

mark1_foreground #2d3134
mark1_background #626569
mark2_foreground #2f3032
mark2_background #4b4b4d
mark3_foreground #362f28
mark3_background #6c635b

active_tab_foreground #2d3134
active_tab_background #c4c6cb
inactive_tab_foreground #c5c6ca
inactive_tab_background #201f20

active_border_color #c4c6cb
inactive_border_color #c5c6ca